name: Build Image

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create .env.production file
        run: |
          echo "${{ secrets.PRODUCTION_DOT_ENV }}" > .env.production


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: 'grubplanner.co.uk:32000'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: grubplanner.co.uk:32000/meals_web_client:latest
  deploy:
    needs: build_image
    runs-on: ubuntu-latest
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.31.5'

      - name: Configure kubectl
        run: |
          echo -n "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig
          kubectl config set-context --current --kubeconfig=kubeconfig
          kubectl config view
      - name: Restart deployment
        run: |
          kubectl rollout restart deployment meals-web-client --kubeconfig=kubeconfig